## Huffman Coding (Including compressing and decompressing the file)

In [1]:
import pandas as pd
import numpy as np

In [2]:
from IPython.display import display_html
def display_side_by_side(*args):
    html_str=''
    for df in args:
        html_str+=df.to_html()
    display_html(html_str.replace('table','table style="display:inline"'),raw=True)

In [3]:
with open('song.txt','r') as file:
    lines = []
    for line in file:
        lines.append(line[:-1])
        
original = " ".join(lines)
print(original)

Empty spaces, what are we living for? Abandoned places, I guess we know the score, on and on Does anybody know what we are looking for? Another hero, another mindless crime Behind the curtain, in the pantomime Hold the line Does anybody want to take it anymore? The show must go on The show must go on, yeah Inside my heart is breaking My makeup may be flaking But my smile, still, stays on Whatever happens, I'll leave it all to chance Another heartache, another failed romance, on and on Does anybody know what we are living for? I guess I'm learning I must be warmer now I'll soon be turning, round the corner now Outside the dawn is breaking But inside in the dark I'm aching to be free The show must go on The show must go on Inside my heart is breaking My makeup may be flaking But my smile, still, stays on My soul is painted like the wings of butterflies Fairy tales of yesterday, grow but never die I can fly, my friends The show must go on The show must go on I'll face it with a grin I'm never giving in On with the show I'll top the bill I'll overkill I have to find the will to carry on On with the show Show Show must go on, go on, go on, go on, go on, go on, go on, go on

In [4]:
#DataCamp, ehm I mean, UPY courses paying off
freq={key: original.count(key) for key in original}

# Show Output
print ("Per char frequency is :\n {}".format(str(freq)))

Per char frequency is :
 {'E': 1, 'm': 30, 'p': 10, 't': 63, 'y': 26, ' ': 239, 's': 53, 'a': 58, 'c': 14, 'e': 96, ',': 23, 'w': 31, 'h': 50, 'r': 43, 'l': 41, 'i': 56, 'v': 9, 'n': 81, 'g': 32, 'f': 14, 'o': 87, '?': 4, 'A': 3, 'b': 15, 'd': 23, 'I': 15, 'u': 22, 'k': 15, 'D': 3, 'B': 4, 'H': 1, 'T': 6, 'M': 3, 'W': 1, "'": 8, 'O': 3, 'F': 1, 'S': 2}

In [5]:
main_table=pd.DataFrame(data = {'Character': list(freq.keys()),'Frequency': list(freq.values())}).sort_values(by='Frequency').reset_index().drop(columns='index')
display_side_by_side(main_table.head(),main_table.tail())

,Character,Frequency
0,E,1
1,W,1
2,H,1
3,F,1
4,S,2
,Character,Frequency
33,t,63
34,n,81
35,o,87
36,e,96
37,,239

In [6]:
total_char_freq=sum(main_table.Frequency)
print("Total character frequency found",total_char_freq)

Total character frequency found 1186

In [7]:
total_char=main_table.Character.count()
print("Total number of characters found (linespace counts as a regular space)", total_char)

Total number of characters found (linespace counts as a regular space) 38

In [8]:
main_table['Probability'] = main_table['Frequency'] / total_char_freq
main_table['Log2(p)'] = np.log2(main_table.Probability)
main_table['p * log2(p)'] = main_table['Log2(p)'] * main_table.Probability

In [9]:
display_side_by_side(main_table.head(),main_table.tail())

,Character,Frequency,Probability,Log2(p),p * log2(p)
0,E,1,0.000843,-10.211888,-0.008610
1,W,1,0.000843,-10.211888,-0.008610
2,H,1,0.000843,-10.211888,-0.008610
3,F,1,0.000843,-10.211888,-0.008610
4,S,2,0.001686,-9.211888,-0.015534
,Character,Frequency,Probability,Log2(p),p * log2(p)
33,t,63,0.053120,-4.234608,-0.224941
34,n,81,0.068297,-3.872038,-0.264448
35,o,87,0.073356,-3.768945,-0.276474
36,e,96,0.080944,-3.626926,-0.293579
37,,239,0.201518,-2.311021,-0.465712

In [10]:
entropy=sum(main_table['p * log2(p)'])*-1
print("Calculated entropy:", entropy)

Calculated entropy: 4.32258302671316

In [11]:
encoding=['1000011110','1110100000','1000011111','1110100001','100001110','111010110','111010001','111010100','111010101','111010111',
          '10000110','11101001','1000010','1010100','1010101','010100','010101','100000','011000','011001','101011','110010','110011',
          '111011','01011','01101','10001', '10100','11000','11100','11110','11111','0100','0111','1001','1011','1101','00']

In [12]:
main_table['Encoding']=encoding
main_table['Length']=main_table.Encoding.str.len()
main_table['Total_Length']=main_table.Length*main_table.Frequency

In [13]:
display(main_table)

,Character,Frequency,Probability,Log2(p),p * log2(p),Encoding,Length,Total_Length
0,E,1,0.000843,-10.211888,-0.008610,1000011110,10,10
1,W,1,0.000843,-10.211888,-0.008610,1110100000,10,10
2,H,1,0.000843,-10.211888,-0.008610,1000011111,10,10
3,F,1,0.000843,-10.211888,-0.008610,1110100001,10,10
4,S,2,0.001686,-9.211888,-0.015534,100001110,9,18
5,O,3,0.002530,-8.626926,-0.021822,111010110,9,27
6,A,3,0.002530,-8.626926,-0.021822,111010001,9,27
7,D,3,0.002530,-8.626926,-0.021822,111010100,9,27
8,M,3,0.002530,-8.626926,-0.021822,111010101,9,27
9,?,4,0.003373,-8.211888,-0.027696,111010111,9,36
10,B,4,0.003373,-8.211888,-0.027696,10000110,8,32
11,T,6,0.005059,-7.626926,-0.038585,11101001,8,48
12,',8,0.006745,-7.211888,-0.048647,1000010,7,56
13,v,9,0.007589,-7.041963,-0.053438,1010100,7,63
14,p,10,0.008432,-6.889960,-0.058094,1010101,7,70
15,c,14,0.011804,-6.404533,-0.075602,010100,6,84
16,f,14,0.011804,-6.404533,-0.075602,010101,6,84
17,k,15,0.012648,-6.304998,-0.079743,100000,6,90
18,b,15,0.012648,-6.304998,-0.079743,011000,6,90
19,I,15,0.012648,-6.304998,-0.079743,011001,6,90
20,u,22,0.018550,-5.752457,-0.106707,101011,6,132
21,d,23,0.019393,-5.688326,-0.110313,110010,6,138
22,",",23,0.019393,-5.688326,-0.110313,110011,6,138
23,y,26,0.021922,-5.511449,-0.120824,111011,6,156
24,m,30,0.025295,-5.304998,-0.134190,01011,5,150
25,w,31,0.026138,-5.257692,-0.137427,01101,5,155
26,g,32,0.026981,-5.211888,-0.140624,10001,5,160
27,l,41,0.034570,-4.854336,-0.167814,10100,5,205
28,r,43,0.036256,-4.785624,-0.173509,11000,5,215
29,h,50,0.042159,-4.568032,-0.192581,11100,5,250
30,s,53,0.044688,-4.483968,-0.200380,11110,5,265
31,i,56,0.047218,-4.404533,-0.207971,11111,5,280
32,a,58,0.048904,-4.353907,-0.212923,0100,4,232
33,t,63,0.053120,-4.234608,-0.224941,0111,4,252
34,n,81,0.068297,-3.872038,-0.264448,1001,4,324
35,o,87,0.073356,-3.768945,-0.276474,1011,4,348
36,e,96,0.080944,-3.626926,-0.293579,1101,4,384
37,,239,0.201518,-2.311021,-0.465712,00,2,478

In [14]:
total_encoding_freq=sum(main_table.Total_Length)
print("Total encoding frequency: ",total_encoding_freq)

Total encoding frequency:  5171

## "Compressing"

In [15]:
#hash-ish
code_dict=pd.Series(main_table.Encoding.values,index=main_table.Character.values).to_dict()
print(code_dict)

{'E': '1000011110', 'W': '1110100000', 'H': '1000011111', 'F': '1110100001', 'S': '100001110', 'O': '111010110', 'A': '111010001', 'D': '111010100', 'M': '111010101', '?': '111010111', 'B': '10000110', 'T': '11101001', "'": '1000010', 'v': '1010100', 'p': '1010101', 'c': '010100', 'f': '010101', 'k': '100000', 'b': '011000', 'I': '011001', 'u': '101011', 'd': '110010', ',': '110011', 'y': '111011', 'm': '01011', 'w': '01101', 'g': '10001', 'l': '10100', 'r': '11000', 'h': '11100', 's': '11110', 'i': '11111', 'a': '0100', 't': '0111', 'n': '1001', 'o': '1011', 'e': '1101', ' ': '00'}

In [16]:
encoded_text=original
for i in code_dict:
    encoded_text = encoded_text.replace(i, code_dict[i])

In [17]:
print("Character frequency found in compressed text",len(encoded_text))

Character frequency found in compressed text 5171

In [18]:
print(encoded_text)

10000111100101110101010111111011001111010101010100010100110111110110011000110111100010001110001001100011010001101110100101001111110101001111110011000100010101101111000111010111001110100010110000100100111001010111001110111001000101010110100010001010011011111011001100011001001000110101111011111011110000110111010010000010011011011010001111110011010011110010100101111000110111001100101110010001001001110010001011100100111010100101111011111000010010011110110110001011110010111011001000001001101101101000110111100010001110001101110100010011000110100101001011101110000011111100110001000101011011110001110101110011101000110011011011111100110111000001110011011100010111100110001001001101101111110011011100000010111111110011100101010011011111011110000101001100011111010111101001000011011011110011111100111001000011111100110100010100101011110000111010011111100111001100111111001000111111001101001010101010010010111101101011111110101111010010000111111011101001100100001111110011010010100111111001110100111010100101111011111000010010011110110110001011110010111011000110101001001011100011110110001110100100000110100111110111000100100111101101011101111000110111101011100111010011110011010011110111001011011010001011101011111100111001000110110010111001001110100111100110100111101110010110110100010111010111111001110010001101100101110011100110011101111010100111000001100110011111011111110010110100010111110110011100110101001100001110011111111100001100011000110101001000001111110011000100111010101111011000101101001000001101101011101010100010110100111011000110001101000101011010001001000001111110011000100100001101010110111000101111101100111100101111111101001101110011001111001111111110100101001100110011110011101001110111111000101110010011101000001110001000111110110101001101110000011100010010101011010101110110011111011001100011001100001010100101000010100110101001010100110100111110111000100101001010000011110110001010011100010010010101001101001110100011001101101111110011011100000111001101010011000011101000101001110011011100110001001001101101111110011011100000010101010011111101001101110010001100010110101101001001010100110111001100101110010001001001110010001011100100111010100101111011111000010010011110110110001011110010111011001000001001101101101000110111100010001110001101110100010011000110100101001111110101001111110011000100010101101111000111010111000110010010001101011110111110111100001100110000100101100101001101010011000100111111100110001000110010001011101011111100111000110001101000110101001100001011110111000001001101101101000110011000010101001010000111101011101110010001100011010001111010111100010011111110011000111001100110001011101011100111001000011111100110100010100101111000100111011100000100110110110100111010110101011011111110111111100101101000111111001101001100100100011011001001111111110000110001100011010100100000111111001100010010000110101011011100111111001111101111111001011010011111100100011111100110100110010010011000100000000110011000010010110001000101001110011111100110001000111101100011000110100010101110001101110100111010011110011010011110111001011011010001011101011111100111001000110110010111001001110100111100110100111101110010110110100010111010111111001110010001101100101110010001100110011111011111110010110100010111110110011100110101001100001110011111111100001100011000110101001000001111110011000100111010101111011000101101001000001101101011101010100010110100111011000110001101000101011010001001000001111110011000100100001101010110111000101111101100111100101111111101001101110011001111001111111110100101001100110011110011101001110111111000101110010011101010111101100111101011101011101000011111111100010101010100111111001011111011100100010100111111000001101000111111001101000110111111100110001111100010110101010001100010101101110111110111000010101101001111111011111000111010000101001111111000111011000111010010100110111110001011010101001110111101111100111110111000110010010011101111001100100011100010110110100011000101011011100100111011010100110111000001100101111111010001100100010100010010010001010110100111011110011000101111101100010101110001111111011001110010111100011101001111001101001111011100101101101000101110101111110011100100011011001011100100111010011110011010011110111001011011010001011101011111100111001000110110010111001000110011000010101001010000010101010001010011010011111011100011011111101111110000010000100011100011111100100011001100001001011001001110110101001101110000010001111111010100111111001100010011111100100111010110100100011011111101111110000011111100110100111101110010110110100011001100001010100101000001111011101010100011111100110100011000111111010010100000110011000010101001010000101110101001101110001000001111110100101000001100100111000100101010011010001111011000101011111110011100100001111110011010001101111111010010100000111101100010100010011000110001110110010111001001110101101001000110111111011111100000111111001101001111011100101101101001000011101110010110110100100001110111001011011010001011101011111100111001000110110010111001110011001000110110010111001110011001000110110010111001110011001000110110010111001110011001000110110010111001110011001000110110010111001110011001000110110010111001110011001000110110010111001

## Decompressing

In [19]:
decoded_text = ''
for i in range(len(original)):
    for char, code in code_dict.items():
        try:
            post = encoded_text.index(code)
            if post == 0:
                decoded_text = decoded_text + char
                encoded_text = encoded_text[len(code):]
        except:
            continue

In [20]:
print(decoded_text)

Empty spaces, what are we living for? Abandoned places, I guess we know the score, on and on Does anybody know what we are looking for? Another hero, another mindless crime Behind the curtain, in the pantomime Hold the line Does anybody want to take it anymore? The show must go on The show must go on, yeah Inside my heart is breaking My makeup may be flaking But my smile, still, stays on Whatever happens, I'll leave it all to chance Another heartache, another failed romance, on and on Does anybody know what we are living for? I guess I'm learning I must be warmer now I'll soon be turning, round the corner now Outside the dawn is breaking But inside in the dark I'm aching to be free The show must go on The show must go on Inside my heart is breaking My makeup may be flaking But my smile, still, stays on My soul is painted like the wings of butterflies Fairy tales of yesterday, grow but never die I can fly, my friends The show must go on The show must go on I'll face it with a grin I'm never giving in On with the show I'll top the bill I'll overkill I have to find the will to carry on On with the show Show Show must go on, go on, go on, go on, go on, go on, go on, go on

In [21]:
print("Character frequency found in decompressed file",len(decoded_text))

Character frequency found in decompressed file 1186

In [22]:
## Building tuples

In [23]:
tuples = []
for char in freq.keys() :
    tuples.append((freq[char],char))
tuples.sort()

In [24]:
print(tuples)

[(1, 'E'), (1, 'F'), (1, 'H'), (1, 'W'), (2, 'S'), (3, 'A'), (3, 'D'), (3, 'M'), (3, 'O'), (4, '?'), (4, 'B'), (6, 'T'), (8, "'"), (9, 'v'), (10, 'p'), (14, 'c'), (14, 'f'), (15, 'I'), (15, 'b'), (15, 'k'), (22, 'u'), (23, ','), (23, 'd'), (26, 'y'), (30, 'm'), (31, 'w'), (32, 'g'), (41, 'l'), (43, 'r'), (50, 'h'), (53, 's'), (56, 'i'), (58, 'a'), (63, 't'), (81, 'n'), (87, 'o'), (96, 'e'), (239, ' ')]